feat: (ТЗ 13, ред. 1.0)
IcelandicMan/java-shareit pull request #1
Opened 2023-08-11 11:31 UTC by IcelandicMan

добавлены CRUD операции по пользователям и вещам, а так же поиск вещи по параметрам

2023-08-11 16:14 UTC, YazykovMikhail requested changes

2023-08-11 16:14 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") Long userId, @RequestBody @Valid ItemDto item) {
Вообще лучше делать dto под каждый запрос, потому что везде нудны только свои поля.
Например:
CreateItemRequestDto
CreateItemResponseDto 

ну ответ может быть и один на всех, если там все поля совпадают, но запрос лучше разделять, я вот открывать метод создания, открываю тут ItemDto а там есть id, а зачем id приходит при создании? или так должно быть? сразу вопросы

2023-08-11 16:14 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +
стоит сделать отдельное поле для проверки уникальности емейлов
	private final Set<String> emailUniqSet = new HashSet<>();
это будет тоже самое что индекс в БД

и соотвественно сохранение будет выглядеть  как т отак:

```
public User save(User user) {
		final String email = user.getEmail();
		if (emailUniqSet.contains(email)) {
			throw new DataAlreadyExistException("Email: " + email + " already exists");
		}
		user.setId(++counter);
		storage.put(user.getId(), user);
		emailUniqSet.add(email);
		return user;
	}
```
а обновление так:

```
public void update(User user) {
		final String email = user.getEmail();
		storage.computeIfPresent(user.getId(), (id, u) -> {
					if (!email.equals(u.getEmail())) {
						if (emailUniqSet.contains(email)) {
							throw new DataAlreadyExistException("Email: " + email + " already exists");
						}
						emailUniqSet.remove(u.getEmail());
						emailUniqSet.add(email);
					}
					return user;
				}
		);

	}
```

2023-08-11 16:14 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +            // Ничего не делаем, потому что адрес электронной почты остался неизменным
звучит не очень) 
предложил решение

2023-08-11 16:14 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    private final Map<Long, Map<Long, Item>> userItemsMap = new HashMap<>();
лучше сделать обычное хранение:
	private final Map<Long, Item> storage = new LinkedHashMap<>();
где ключ это итем id , а значение сам итем
и отдельно сделать 
	private final Map<Long, List<Item>> userItemIndex = new LinkedHashMap<>();
где ключ это пользователь, а значение это его список итемов. - это тоже будет выглядеть как индекс в БД.

2023-08-11 16:14 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    public Item createItem(Long userId, Item item) {
в репозиторий уже приходит готовая модель Item у него есть поле ownerId там и будет находится userId, не нужно его отедльно сюда ередавать.
Поправь везде репозитооррий работает уже с готовой моделью

2023-08-11 16:14 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    public Item updateItem(Long userId, Long itemId, Item updatedItem) {
только готовая модель

2023-08-11 16:14 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (!text.isBlank()) {
если text пришел null будет NPE 
if (text == null || text.isBlank()) {
			return Collections.emptyList();
		}

2023-08-11 21:31 UTC, IcelandicMan commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") Long userId, @RequestBody @Valid ItemDto item) {
Идею понял, но:
1. По моей логике, после создания желательно сообщить пользователю какой id присвоен его вещи
2. Это требуется в Post тестах 
pm.test("Test item 'id' field", function () {
    var jsonData = pm.response.json();
    pm.expect(jsonData).to.have.property('id');
    pm.expect(jsonData.id, '"id" must be 1').to.eql(1);
});

2023-08-12 08:26 UTC, IcelandicMan commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (!text.isBlank()) {
исправлено

2023-08-12 08:27 UTC, IcelandicMan commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    public Item updateItem(Long userId, Long itemId, Item updatedItem) {
исправлено

2023-08-12 08:27 UTC, IcelandicMan commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    public Item createItem(Long userId, Item item) {
исправлено

2023-08-12 08:53 UTC, IcelandicMan commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +
исправлено

2023-08-12 08:53 UTC, IcelandicMan commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +            // Ничего не делаем, потому что адрес электронной почты остался неизменным
исправлено

2023-08-12 08:58 UTC, IcelandicMan commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    private final Map<Long, Map<Long, Item>> userItemsMap = new HashMap<>();
Использую  HashMap<>, поскольку порядок ключей не имеет значения.

2023-08-12 12:19 UTC, IcelandicMan commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +
public void update(User user) // я все таки предпочитаю возвращать User
И storage.computeIfPresent я разобрал, но все таки решил сделать через обычные if

2023-08-12 14:58 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") Long userId, @RequestBody @Valid ItemDto item) {
Как я написал
запросы и ответы dto должны быть разыне
CreateItemRequestDto
CreateItemResponseDto
в ответе кончено ты передаешь id, но зачем он в запросе?

2023-08-12 16:00 UTC, YazykovMikhail approved these changes

2023-08-28 11:12 UTC, merged