"feat: Добавлено Бронирование и Комментарии согласно 14 ТЗ"
IcelandicMan/java-shareit pull request #2
Opened 2023-08-28 11:09 UTC by IcelandicMan

2023-08-29 15:06 UTC, YazykovMikhail requested changes

2023-08-29 15:06 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (createdBooking.getItem().getAvailable() == false) {
не нужно сранивать булиан занчения в услвоиях, ведь они уже и так буллеа
        if (!createdBooking.getItem().getAvailable()) {

2023-08-29 15:06 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        responseDto.setId(booking.getId());
для такого и существуют маперы, вынеси в мапер

2023-08-29 15:06 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Item item = new Item();
все это в мапер

2023-08-29 15:06 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        createdBooking.setStart(booking.getStart());
Тоже в мапер, пройдись по коду, вынеси в мапер такие большие преопразования в маперры

2023-08-29 15:06 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        } catch (IllegalArgumentException e) {
ты ловишь исключение и потом выкидываешь его же
Непровеяремые исключение можно не проверять, а если уж и провеярешь то сделай свое исключение и выикдывай его

2023-08-29 16:22 UTC, IcelandicMan commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (createdBooking.getItem().getAvailable() == false) {
Да, я передумал себя просто, подумал, что так как 
Available() может иметь два значение true и false, то это сравнение  if (!createdBooking.getItem().getAvailable()) { 
будет работать если  начальное available = true и если же оно не true, т.е false, то выбрасываем исключение
А если же начальное available = false, не будет ли выбрасывается исключение на противоположное значение, т.е на true)

2023-08-30 11:19 UTC, YazykovMikhail approved these changes
Стало ведь лучше, код не увеличился, а уменьшился. 
В сервисе главное видеть главные вызовы, а методы типа .set()
они захламляют код, если кому то нужно посомтреть ккак создается обьект, то он спокойно пойдет в мапер и посмотри.

2023-09-09 07:22 UTC, merged